language: cpp
compiler:
  - clang
os:
  - linux
  - osx
sudo: false
cache: ccache
matrix:
  include:
    - os: linux
      env: LINTER_ONLY=true
before_install:
  - export HOMEBREW_NO_AUTO_UPDATE=1 # work around https://github.com/travis-ci/travis-ci/issues/7456
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install ccache; fi
  - export PATH="/usr/local/opt/ccache/libexec:$PATH"
  - export CXX="ccache clang++ -Qunused-arguments"
  - export CC="ccache clang -Qunused-arguments"
  - export JOBS=2
install:
  - ./configure
  - make -j2 V=
script:
  - tools/run-ci.sh # do linter env variable detection
